-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 22:05:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MetaViews
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MetaViews` ;

-- -----------------------------------------------------
-- Schema MetaViews
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MetaViews` DEFAULT CHARACTER SET utf8 ;
USE `MetaViews` ;

-- -----------------------------------------------------
-- Table `MetaViews`.`Midia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MetaViews`.`Midia` ;

CREATE TABLE IF NOT EXISTS `MetaViews`.`Midia` (
  `idMidia` INT NOT NULL AUTO_INCREMENT,
  `duracao` FLOAT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `tipo` TINYINT NOT NULL,
  `diretor` VARCHAR(180) NOT NULL,
  `classificacaoIndicatica` TINYINT(1) NOT NULL,
  `sinopse` MEDIUMTEXT NOT NULL,
  `dataLancamento` DATE NOT NULL,
  `generos` VARCHAR(180) NULL,
  `plataformas` VARCHAR(180) NULL,
  PRIMARY KEY (`idMidia`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMidia_UNIQUE` ON `MetaViews`.`Midia` (`idMidia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `MetaViews`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MetaViews`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `MetaViews`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(180) NOT NULL,
  `idade` TINYINT(1) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUsuario_UNIQUE` ON `MetaViews`.`Usuario` (`idUsuario` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `MetaViews`.`Usuario` (`email` ASC) VISIBLE;

CREATE UNIQUE INDEX `nome_UNIQUE` ON `MetaViews`.`Usuario` (`nome` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `MetaViews`.`Assistira`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MetaViews`.`Assistira` ;

CREATE TABLE IF NOT EXISTS `MetaViews`.`Assistira` (
  `Usuario_idUsuario` INT NOT NULL,
  `Midia_idMidia` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Midia_idMidia`),
  CONSTRAINT `fk_Usuario_has_Midia_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `MetaViews`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuario_has_Midia_Midia1`
    FOREIGN KEY (`Midia_idMidia`)
    REFERENCES `MetaViews`.`Midia` (`idMidia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Midia_Midia1_idx` ON `MetaViews`.`Assistira` (`Midia_idMidia` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_has_Midia_Usuario_idx` ON `MetaViews`.`Assistira` (`Usuario_idUsuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `MetaViews`.`Avalia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MetaViews`.`Avalia` ;

CREATE TABLE IF NOT EXISTS `MetaViews`.`Avalia` (
  `Usuario_idUsuario` INT NOT NULL,
  `Midia_idMidia` INT NOT NULL,
  `Nota` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Midia_idMidia`),
  CONSTRAINT `fk_Usuario_has_Midia_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `MetaViews`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuario_has_Midia_Midia2`
    FOREIGN KEY (`Midia_idMidia`)
    REFERENCES `MetaViews`.`Midia` (`idMidia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Midia_Midia2_idx` ON `MetaViews`.`Avalia` (`Midia_idMidia` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_has_Midia_Usuario1_idx` ON `MetaViews`.`Avalia` (`Usuario_idUsuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
