-- MySQL Script generated by MySQL Workbench
-- Wed Sep 14 21:40:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MetaViewer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MetaViewer` ;

-- -----------------------------------------------------
-- Schema MetaViewer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MetaViewer` DEFAULT CHARACTER SET utf8 ;
USE `MetaViewer` ;

-- -----------------------------------------------------
-- Table `MetaViewer`.`Midia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MetaViewer`.`Midia` ;

CREATE TABLE IF NOT EXISTS `MetaViewer`.`Midia` (
  `idMidia` INT NOT NULL AUTO_INCREMENT,
  `duracao` FLOAT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `tipo` TINYINT NOT NULL,
  `diretor` VARCHAR(180) NOT NULL,
  `classificacaoIndicatica` TINYINT(1) NOT NULL,
  `sinopse` MEDIUMTEXT NOT NULL,
  `dataLancamento` DATE NOT NULL,
  `generos` VARCHAR(180) NOT NULL,
  `plataformas` VARCHAR(180) NOT NULL,
  PRIMARY KEY (`idMidia`),
  UNIQUE INDEX `idMidia_UNIQUE` (`idMidia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MetaViewer`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MetaViewer`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `MetaViewer`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(180) NOT NULL,
  `idade` TINYINT(1) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MetaViewer`.`Assistira`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MetaViewer`.`Assistira` ;

CREATE TABLE IF NOT EXISTS `MetaViewer`.`Assistira` (
  `Usuario_idUsuario` INT NOT NULL,
  `Midia_idMidia` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Midia_idMidia`),
  INDEX `fk_Usuario_has_Midia_Midia1_idx` (`Midia_idMidia` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Midia_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Midia_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `MetaViewer`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Midia_Midia1`
    FOREIGN KEY (`Midia_idMidia`)
    REFERENCES `MetaViewer`.`Midia` (`idMidia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MetaViewer`.`Avalia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MetaViewer`.`Avalia` ;

CREATE TABLE IF NOT EXISTS `MetaViewer`.`Avalia` (
  `Usuario_idUsuario` INT NOT NULL,
  `Midia_idMidia` INT NOT NULL,
  `Nota` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Midia_idMidia`),
  INDEX `fk_Usuario_has_Midia_Midia2_idx` (`Midia_idMidia` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Midia_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Midia_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `MetaViewer`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Midia_Midia2`
    FOREIGN KEY (`Midia_idMidia`)
    REFERENCES `MetaViewer`.`Midia` (`idMidia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
